pipeline {
    agent any

    environment {
        APP_NAME = "bookmark-api"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/km-saifullah/bookmark-api.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
                echo 'Dependency Installation Done...!'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Test Done'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker compose build'
                echo 'All the build done...!'
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                    docker compose down
                    docker compose up -d --build --scale backend=4
                '''
                echo ''
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker image prune -f'
                echo "All images removed successfully...!"
            }
        }
    }
}